services:
  - type: web
    name: nexura-server
    env: node
    plan: free
    buildCommand: cd server && npm install && npx prisma generate && npm run build
    startCommand: cd server && npx prisma migrate deploy && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexura-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 20.12.2

  - type: static_site
    name: nexura-client
    plan: free
    buildCommand: cd client && npm install && npm run build
    publishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: nexura-server
          property: url

databases:
  - name: nexura-db
    plan: free
    databaseName: nexura
    user: nexura
